[package]
name = "hub"
version = "0.1.0"
edition = "2024"

[dependencies]
evm = { path = "../evm" }
solarium = { path = "../../solarium" }
solana = { path = "../solana" }
anyhow = "1.0.99"
futures-util = "0.3"
petgraph = "0.8.2"
rust_decimal = { version = "1.37.2", features = ["maths"] }
rust_decimal_macros = "1.36"
tokio = { version = "1.47.1", features = ["full"] }
